### ISSUE TITLE
Evento de prueba

### ISSUE THREAD

**Issue by raulvillares** [comunidadcode/eventos#2]
Este es un evento de prueba.

**EVENTO DE PRUEBA**
Speaker: Nadie
Jueves 21 de Septiembre 2017
19:00h (España peninsular)

**Comment by raulvillares** [comment]
Y si comento algo avisa por email?

**Comment by pepitofernandez** [comment]
#RVSP

**Comment by raulvillares** [comment]
Pongo un mensaje aquí a ver si le llega un mail a pepito.

**Comment by pepitofernandez** [comment]
Sí me ha llegado, pero yo a este vente paso de ir. Así que "unsuscribe"!
